version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8090:8090"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb

  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enrollment.enabled: "true"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
#    networks:
#      - lab-logging-network

  kibana:
    image: kibana:8.8.0
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
#    networks:
#      - lab-logging-network


  #  app:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    container_name: notiefy-app
  #    ports:
  #      - "8081:8081"
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notiefy-db
  #      SPRING_DATASOURCE_USERNAME: postgres
  #      SPRING_DATASOURCE_PASSWORD: postgres
  #    depends_on:
  #      - postgres
  #      - rabbitmq
  #    restart: always


#networks:
#  lab-logging-network:
#    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
