spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/book-db
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    virtual-host: /

rabbitmq:
  queues:
    student-created: bookCreated
    student-updated: bookUpdated
    student-deleted: bookDeleted

server:
  port: 8082
